/**
 * 这个文件主要是干什么的：
 * 定义“问题” (Question) 的数据结构。
 * 一个 Question 可以对应多张 Card（例如 Cloze 题可能有多个空，或者正反向题有两张卡）。
 * 它负责管理问题的文本内容、Obsidian Block ID 以及 HTML 调度注释的读写。
 *
 * 它在项目中属于：模型层 (Model Layer)
 *
 * 它会用到哪些文件：
 * 1. src/Card.ts (包含的卡片)
 * 2. src/TopicPath.ts (所属的 Tag 路径)
 *
 * 哪些文件会用到它：
 * 1. src/Note.ts (笔记由问题组成)
 * 2. src/NoteQuestionParser.ts (解析生成 Question)
 * 3. src/FlashcardReviewSequencer.ts (复习时操作的对象)
 */
/**
 * [模型] 代表一个问题（可能生成多张卡片，如正反向）。
 */
import { Card } from "./Card";
import { NoteCardScheduleParser } from "./CardSchedule";
import { OBSIDIAN_BLOCK_ID_ENDOFLINE_REGEX, OBSIDIAN_TAG_AT_STARTOFLINE_REGEX } from "./constants";
import { Note } from "./Note";
import { ParsedQuestionInfo } from "./parser";
import { SRSettings } from "./settings";
import { TopicPath, TopicPathList, TopicPathWithWs } from "./TopicPath";
import { MultiLineTextFinder } from "./util/MultiLineTextFinder";
import { TextDirection } from "./util/TextDirection";
import { cyrb53, stringTrimStart } from "./util/utils";

export enum CardType {
    SingleLineBasic,
    SingleLineReversed,
    MultiLineBasic,
    MultiLineReversed,
    Cloze,
    AnkiCloze, // Anki 风格 {{c1::...}} 挖空
}

//
// QuestionText comprises the following components:
//      1. QuestionTopicPath (optional, and if present there may be whitespace before)
//
//      2. Actual question text (mandatory)
//
//      3. Card schedule info as HTML comment (optional). If present then there is
//          optional whitespace after the question text, before this.
//          (whitespace always included when text is generated by formatForNote(), would only
//          be missing if manually removed by the user)
//
//      4. Obsidian block identifier (optional)
//
// Actual Question - Whitespace Handling
//
//      It is important that whitespace is maintained accurately by this class.
//
//      **Leading Whitespace**
//
//          It's important to retain the leading whitespace in the case where there is no QuestionTopicPath,
//          as leading whitespace is an indicator in markdown of the indent level.
//          see "[BUG] Problem with nested list item's indentation"
// Legacy regression note retained from an earlier parsing edge case.
//
//          In the case where QuestionTopicPath is present, whitespace pre and post QuestionTopicPath
//          are retained so that if the question is written back to the file, for aesthetic reasons
//          there won't be any change to the whitespace.
//
//          However, actualQuestion will not have any leading spaces.
//
//      **Trailing Whitespace**
//
//         Trailing whitespace is always removed.
//
//         This is because Question.formatForNote() uses the whitespace generated by Question.getHtmlCommentSeparator()
//         as the separator between the end of the question text and the OSR html comment -
//         either a single space or a new line (settings based)
//
// For example
//
//  Actual question text only:
//      Q1::A1
//
//  Question text with topic path:
//      #flashcards/science  Q2::A2
//
//  Question text with card schedule info:
//      #flashcards/science  Q2::A2 <!--SR:!2023-10-16,34,290-->
//
//  Question text with card schedule info and block identifier:
//      #flashcards/science  Q2::A2 <!--SR:!2023-10-16,34,290--> ^d7cee0
//
//  Question text with block identifier:
//      Q2::A2 ^d7cee0
//
export class QuestionText {
    // Complete text including all components, as read from file
    original: string;

    // The question topic path (only present if topic path included in original text)
    // If present, it also includes whitespace before and after the topic path itself
    topicPathWithWs: TopicPathWithWs;

    // The question text, e.g. "Q1::A1" with leading/trailing whitespace as described above
    actualQuestion: string;

    // Either LTR or RTL
    textDirection: TextDirection;

    // The block identifier (optional), e.g. "^quote-of-the-day"
    // Format of block identifiers:
    //      https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note
    //      Block identifiers can only consist of letters, numbers, and dashes.
    // If present, then first character is "^"
    obsidianBlockId: string;
    genBlockId?: string;

    // Hash of string  (topicPath + actualQuestion)
    // Explicitly excludes the HTML comment with the scheduling info
    textHash: string;

    constructor(
        original: string,
        topicPathWithWs: TopicPathWithWs,
        actualQuestion: string,
        textDirection: TextDirection,
        blockId: string,
    ) {
        this.original = original;
        this.topicPathWithWs = topicPathWithWs;
        this.actualQuestion = actualQuestion;
        this.textDirection = textDirection;
        this.obsidianBlockId = blockId;

        // The hash is generated based on the topic and question, explicitly not the schedule or obsidian block ID
        this.textHash = cyrb53(this.formatTopicAndQuestion());
    }

    endsWithCodeBlock(): boolean {
        return this.actualQuestion.endsWith("```");
    }

    static create(
        original: string,
        textDirection: TextDirection,
        settings: SRSettings,
    ): QuestionText {
        const [topicPathWithWs, actualQuestion, blockId] = this.splitText(original, settings);

        return new QuestionText(original, topicPathWithWs, actualQuestion, textDirection, blockId);
    }

    static splitText(original: string, settings: SRSettings): [TopicPathWithWs, string, string] {
        const originalWithoutSR = NoteCardScheduleParser.removeCardScheduleInfo(original);
        let actualQuestion: string = originalWithoutSR.trimEnd();

        let topicPathWithWs: TopicPathWithWs = null;
        let blockId: string = null;

        // originalWithoutSR - [[preTopicPathWs] TopicPath [postTopicPathWs]] Question [whitespace blockId]
        const topicPath = TopicPath.getTopicPathFromCardText(originalWithoutSR);
        if (topicPath?.hasPath) {
            // cardText2 - TopicPath postTopicPathWs Question [whitespace blockId]
            const [preTopicPathWs, cardText2] = stringTrimStart(originalWithoutSR);

            // cardText3 - postTopicPathWs Question [whitespace blockId]
            const cardText3: string = cardText2.replaceAll(OBSIDIAN_TAG_AT_STARTOFLINE_REGEX, "");

            // actualQuestion - Question [whitespace blockId]
            let postTopicPathWs: string = null;
            [postTopicPathWs, actualQuestion] = stringTrimStart(cardText3);
            if (!settings.convertFoldersToDecks) {
                topicPathWithWs = new TopicPathWithWs(topicPath, preTopicPathWs, postTopicPathWs);
            }
        }

        // actualQuestion - Question [whitespace blockId]
        [actualQuestion, blockId] = this.extractObsidianBlockId(actualQuestion);

        return [topicPathWithWs, actualQuestion, blockId];
    }

    static extractObsidianBlockId(text: string): [string, string] {
        let question: string = text;
        let blockId: string = null;
        const match = text.match(OBSIDIAN_BLOCK_ID_ENDOFLINE_REGEX);
        if (match) {
            blockId = match[0].trim();
            const newLength = question.length - blockId.length;
            question = question.substring(0, newLength).trimEnd();
        }
        return [question, blockId];
    }

    formatTopicAndQuestion(): string {
        let result: string = "";
        if (this.topicPathWithWs) {
            result += this.topicPathWithWs.formatWithWs();
        }

        result += this.actualQuestion;
        return result;
    }
}

export class Question {
    note: Note;
    parsedQuestionInfo: ParsedQuestionInfo;
    topicPathList: TopicPathList;
    questionText: QuestionText;
    hasEditLaterTag: boolean;
    questionContext: string[];
    cards: Card[];
    hasChanged: boolean;

    get questionType(): CardType {
        return this.parsedQuestionInfo.cardType;
    }
    get lineNo(): number {
        return this.parsedQuestionInfo.firstLineNum;
    }

    constructor(init?: Partial<Question>) {
        Object.assign(this, init);
    }

    setCardList(cards: Card[]): void {
        this.cards = cards;
        this.cards.forEach((card) => (card.question = this));
    }

    formatForNote(settings: SRSettings): string {
        return this.questionText.formatTopicAndQuestion();
    }

    getHtmlCommentSeparator(settings: SRSettings): string {
        if (this.questionText.endsWithCodeBlock()) {
            return "\n";
        }

        return settings.cardCommentOnSameLine ? " " : "\n";
    }

    updateQuestionText(noteText: string, settings: SRSettings): string {
        // Get the entire text for the question including:
        //      1. the topic path (if present),
        //      2. the question text
        //      3. the schedule HTML comment (if present)
        const replacementText = this.formatForNote(settings);
        const originalText: string = this.questionText.original;

        let newText = MultiLineTextFinder.findAndReplace(noteText, originalText, replacementText);
        if (newText) {
            // Don't support changing the textDirection setting
            this.questionText = QuestionText.create(
                replacementText,
                this.questionText.textDirection,
                settings,
            );
        } else {
            console.error(
                `updateQuestionText: Text not found: ${originalText.substring(
                    0,
                    100,
                )} in note: ${noteText.substring(0, 100)}`,
            );
            newText = noteText;
        }
        return newText;
    }

    async writeQuestion(settings: SRSettings): Promise<void> {
        const fileText: string = await this.note.file.read();

        const newText: string = this.updateQuestionText(fileText, settings);
        await this.note.file.write(newText);
        this.hasChanged = false;
    }

    formatTopicPathList(): string {
        return this.topicPathList.format("|");
    }

    static Create(
        settings: SRSettings,
        parsedQuestionInfo: ParsedQuestionInfo,
        noteTopicPathList: TopicPathList,
        textDirection: TextDirection,
        context: string[],
    ): Question {
        const hasEditLaterTag = parsedQuestionInfo.text.includes(settings.editLaterTag);
        const questionText: QuestionText = QuestionText.create(
            parsedQuestionInfo.text,
            textDirection,
            settings,
        );

        let topicPathList: TopicPathList = noteTopicPathList;
        if (questionText.topicPathWithWs) {
            topicPathList = new TopicPathList([questionText.topicPathWithWs.topicPath]);
        }

        const result: Question = new Question({
            parsedQuestionInfo,
            topicPathList,
            questionText,
            hasEditLaterTag,
            questionContext: context,
            cards: null,
            hasChanged: false,
        });

        return result;
    }
}
